### ISSUE TITLE
可変個のファイルを入力・出力させたい

### ISSUE THREAD

**Issue by beam2d** [pfi/maf#37]
データセットが可変個のファイルからなるケースを考える（例えば画像の集合＋ラベル）。このデータセットを生成したり、これを入力したりするタスクが現状直接書けない。無理やり書こうとすると、このデータセットをtar等で固めたファイルを入出力に使うことになるが、使う度に展開する必要があるのでわずらわしいし無駄なコピーがたくさん必要になる。

**Comment by hiroshinoji** [comment]
現状、source側にディレクトリを指定することは対応できそうだが、target側にディレクトリを指定した場合に問題が生じる。
具体的には、targetにディレクトリを指定したタスクは、必ず再実行されてしまう。

タスクを再実行するかどうかは、以下の runnable_status が判定する。
http://docs.waf.googlecode.com/git/apidocs_17/_modules/waflib/Task.html#Task.runnable_status
問題の箇所は、この中の

``` python
for node in self.outputs:
            try:
                if node.sig != new_sig:
                    return RUN_ME
```

の部分。`node.sig`は、target に指定されたノードが持つ固有の値であり、これは前回同じタスクが実行されていれば、実行完了時にノードに値が設定されており（`post_run`）、それが読み込まれる。`new_sig`はタスクの設定状態（入力ファイルのノードなど）から計算されるハッシュ値である。通常の再実行ではこれらの値が等しくなり、実行は行われない。

現状、source, target に指定したパスは、`Node.find_or_declare`
http://docs.waf.googlecode.com/git/apidocs_17/_modules/waflib/Node.html#Node.find_or_declare
によって、ノードに変換される。しかし、ここでディレクトリに対しては、`node.sig = None`とされてしまい、前回実行時に保存された値が`None`で上書きされてしまう。

**Comment by hiroshinoji** [comment]
### 補足

Nodeオブジェクトのメソッドとして、ファイルの探索を行うものは以下のものがある。
以下、`bld`はbuild/ディレクトリ、`src`は実行ディレクトリを指す。
- `find_or_declare`: `bld`->`src`の順で、指定したパスのノードを探し、存在しない場合はノードを作る。見つかったノードがディレクトリの場合、`sig`の値が`None`に設定される。
- `find_resource`: `bld`->`src`の順で、指定したパスのノードを探す。ディレクトリの場合`None`を返す。
- `find_dir`: 現在のノードからの相対パスに存在するディレクトリのノードを探す
- `search_node`: 現在のノードから、相対パスに存在するノードを探す。`find_dir`などと異なり、実際にファイルが存在していても、新しいノードは作成しない。

ここで、`find_resource`は`bld`以下のファイルノードを探すのに対して、`find_dir`は`bld`以下の探索を行わないことに注意する。現在の問題は、targetにディレクトリを指定した場合に、そのノードに保存された`sig`の値が上書きされてしまうことだが、これは`bld`以下に存在するノードである。このノードを探索する手段は、`find_or_declare`もしくは`search_node`しか存在しない。

`find_or_declare`の実装を見ると、まず`bld`に対し`search_node`を実行し、ここでもしディレクトリが見つかった場合、その`sig`を`None`に設定している。従って、もし`find_or_declare`を行わずに、直接`search_node`を実行すれば、`sig`は上書きされずに問題は発生しない。

#### 解決策1

`find_or_declare`を使ってノードの探索を行うことが問題なので、一つの解決策は、ExperimentContext でのノードの探索に`find_or_declare`以外の独自のメソッドを用意すること。

#### 問題点
- そのノードに対してたまたま別の場所で`find_or_declare`が発生すると、その`sig`が書き換えられてしまう。
- ディレクトリの`sig`を`None`に設定することの意義が判明していないので、どこかで副作用が起きる可能性がある。

**Comment by beam2d** [comment]
実装されました。 @nozyh ありがとうございます！
