### ISSUE TITLE
parametersの値としてdictを使うと落ちる

### ISSUE THREAD

**Issue by t-abe** [pfi/maf#39]
```
parameters = [{
  "a": dict(...)
}]
```

上のようなparametersを与えると落ちます。
https://github.com/pfi/maf/blob/master/maflib/core.py#L289 でハッシュをとっているけど、dictに対するhashが定義されていないため。

**Comment by t-abe** [comment]
dictの代わりにmaflib.core.Parameterを使えば大丈夫とのことでした。

**Comment by beam2d** [comment]
dict直書きでも勝手にhashableなdictに変換してくれる仕組みがあっても良いかも。渡した時点でfreezeするイメージで。
