### ISSUE TITLE
出力ファイルを削除したタスクが再実行されない

### ISSUE THREAD

**Issue by hiroshinoji** [pfi/maf#52]
本来、build/experiment 以下の一部のファイルを削除した場合、そのファイルが関わるタスクは全て再実行されないといけないが、これが行われなくなっている。
ディレクトリの入出力に対応した #46 より前のブランチでは正しく再実行されるので、ここでバグが発生したと考えられる。

**Comment by hiroshinoji** [comment]
原因は、変更した `_resolve_meta_node(self, node, parameter)` が、ファイルシステムに存在しないノードも見つけるようになっていたから。
https://github.com/pfi/maf/blob/develop/maflib/core.py#L283 で呼び出している `search_node` は、前回の実行時に保存された `build/experiment` 以下のノードの情報を用いるので、ファイルシステム上で削除されていても、存在するとしてしまう。
よって `search_node` とは別の方法をとるか、`search_node` で見つけた上で、それが実際のファイルシステム上に存在するかを調べないといけない。

**Comment by beam2d** [comment]
マージしました。GJ!
