### ISSUE TITLE
パラメータ付けられた集約タスクが書けない

### ISSUE THREAD

**Issue by beam2d** [pfi/maf#74]
集約タスクに `parameters` を指定しても無視される。以下のwscriptで確認できる。

``` python
import maf
import maflib.util

def configure(conf): pass

def build(exp):
    exp(target='a',
        parameters=maflib.util.product({
            'p': [1, 2],
            'q': [1, 2],
        }),
        rule='echo ${p} ${q} > ${TGT}')

    exp(source='a', target='b',
        aggregate_by='q',  # for_each='p'
        parameters=[{'r': 1}, {'r': 2}],
        rule='echo ${r} > tmp${r}; cat ${SRC} tmp${r} > ${TGT}')
```

このとき最後のタスクは `r=1` と `r=2` の両方で実行されて欲しいが、実際には1回しか実行されず、`${r}` は空になる。`for_each='q r'` のように指定することもできない（この場合key not foundで例外が飛ぶ）。

**Comment by hiroshinoji** [comment]
#87 で対応。未対応な挙動として、 aggregation の際に、これまで定義されたパラメータを再定義した場合がある。現状、何も工夫をしていないので、恐らくどの実行でも、指定したパラメータを用いて上書きされてしまう。しかし通常のタスクのようにフィルタリングを考えだすと複雑すぎる気がする。

**Comment by beam2d** [comment]
対応ありがとうございました
